const JokersData = [
    [
        {name: 'Joker', description: '+4 Mult'},
        {name: 'Chaos the Clown', description: '1 free Reroll per shop'},
        {name: 'Jolly Joker', description: '+8$ Mult if played hand contains a Pair'},
        {name: 'Zany Joker', description: '+12 Mult if played hand contains a Three of a Kind'},
        {name: 'Mad Joker', description: '+20 Mult if played hand contains a Four of a Kind'},
        {name: 'Crazy Joker', description: '+12 Mult if played hand contains a Straight'},
        {name: 'Droll Joker', description: '+10 Mult if played hand contains a Flush'},
        {name: 'Half Joker', description: '+20 Mult if played hand contains 3 or fewer cards'},
        {name: 'Merry Andy', description: '+3 discards, -1 hand size'},
        {name: 'Stone Joker', description: 'This Joker gains +25 Chips for each Stone Card in your full deck (Currently +25 Chips)'}
    ],
    [
        {name: 'Juggler',description: '+1 hand size'},
        {name: 'Drunkard',description: '+1 discard'},
        {name: 'Acrobat',description: 'x3 Mult on final hand of round'},
        {name: 'Sock and Buskin',description: 'Retrigger all played face cards'},
        {name: 'Mime',description: 'Retrigger all card held in hand abilities'},
        {name: 'Credit Card',description: 'Go up to -$20 in debt'},
        {name: 'Greedy Joker',description: 'Played cards with ${diamondc} suit give +4 Mult when scored'},
        {name: 'Lusty Joker',description: 'Played cards with ${heartc} suit give +4 Mult when scored'},
        {name: 'Wrathful Joker',description: 'Played cards with ${spadec} suit give +4 Mult when scored'},
        {name: 'Gluttonous Joker',description: 'Played cards with ${clubc} suit give +4 Mult when scored'}
      ],
      [
        {name:'Troubadour', description: '+2 hand size, -1 hands per round'},
        {name:'Banner', description: '+40 Chips for each remaining discard ${shadowc}(Currently +${jokerValue * 40} Chips)'},
        {name:'Mystic Summit', description: '+15 Mult when 0 discards remaining' },
        {name:'Marble Joker', description: 'Adds one Stone card to deck when Blind is selected'},
        {name:'Loyalty Card', description: '4 Mult every 6 hands played ${shadowc}(${jokerValue % 6} remaining)'},
        {name:'Hack', description: 'Retrigger each played 2, 3, 4, or 5'},
        {name:'Misprint', description: '+0 - +23 Mult'},
        {name:'Steel Joker', description: 'This Joker gains 0.25 Mult for each Steel Card in your full deck ${shadowc}(Currently ${1 + jokerValue * 0.25} Mult)'},
        {name:'Raised Fist', description: 'Adds double the rank of lowest card held in hand to Mult'},
        {name:'Golden Joker', description: 'Earn $4 at end of round'}
      ],
      [
        {name:'Blueprint', description: 'Copies ability of Joker to the right'},
        {name:'Glass Joker', description: 'Gains 0.5 Mult for every Glass Card that is destroyed ${shadowc}(Currently ${1 + jokerValue * 0.5} Mult)'},
        {name:'Scary Face', description: 'Played face cards give +30 Chips when scored'},
        {name:'Abstract Joker', description: '+3 Mult for each Joker card'},
        {name:'Delayed Gratification', description: 'Earn $2 per discard if no discards are used by end of the round'},
        {name:'Golden Ticket', description: 'Played Gold cards earn $3 when scored'},
        {name:'Pareidolia', description: 'All cards are considered Face cards'},
        {name:'Cartomancer', description: 'Create a ${tarotc} card when Blind is selected${roomc}'},
        {name:'Even Steven', description: 'Played cards with even rank give +4 Mult when scored ${shadowc}(10, 8, 6, 4, 2)'},
        {name:'Odd Todd', description: 'Played cards with odd rank give +30 Chips when scored ${shadowc}(A, 9, 7, 5, 3)'}
      ],
      [
        {name: 'Wee Joker', description: 'This Joker gains +8 Chips when each played 2 is scored ${shadowc}(Currently +${10 + jokerValue * 8} Chips)'},
        {name: 'Business Card', description: 'Played Face cards have a ${probc}1 in 2 chance to give $2 when scored'},
        {name: 'Supernova', description: 'Adds the number of times poker hand has been played to Mult'},
        {name: 'Mr. Bones', description: 'Prevents Death if chips scored are at least 25% of required chips self destructs'},
        {name: 'Seeing Double', description: '2 Mult if played hand has a scoring Club card and a scoring card of any other suit'},
        {name: 'The Duo', description: '2 Mult if played hand contains a Pair'},
        {name: 'The Trio', description: '3 Mult if played hand contains a Three of a Kind'},
        {name: 'The Family', description: '4 Mult if played hand contains a Four of a Kind'},
        {name: 'The Order', description: '3 Mult if played hand contains a Straight'},
        {name: 'The Tribe', description: '2 Mult if played hand contains a Flush'}
      ],
      [
        {name: '8 Ball', description: 'Create a ${planetc} card if played hand contains 2 or more 8s${roomc}'},
        {name: 'Fibonacci', description: 'Each plaed Ace, 2, 3, 5, or 8 gives +8 Mult when scored'},
        {name: 'Joker Stencil', description: '1 Mult for each empty Joker slot Joker stencil included ${shadowc}(Currently ${1 + jokerValue})'},
        {name: 'Space Joker', description: '${probc}1 in 4 chane to upgrade level of played poker hand'},
        {name: 'Matador', description: 'Earn $8 if played hand triggers the Boss Blind ability'},
        {name: 'Ceremonial Dagger', description: 'When Blind is selected, destroy Joker to the right and permanently add double its sell value to this Mult ${shadowc}(Currently +${jokerValue * 2} Mult)'},
        {name: 'Showman', description: 'Joker, ${tarotc}, ${planetc}, and ${spectralc} cards may appear multiple times'},
        {name: 'Fortune Teller', description: '+1 Mult per ${tarotc} card used this run ${shadowc}(Currently ${jokerValue})'},
        {name: 'Hit the Road', description: 'Gains 0.5 Mult per discarded Jack this round ${shadowc}(Currently ${1 + jokerValue * 0.5})'},
        {name: 'Swashbuckler', description: 'Adds the sell value of all owned Jokers left of this card to Mult'},
      ],
      [
        {name: 'Flower Pot', description: '3 Mult if played hand has a scoring ${diamondc} card, ${clubc} card, ${heartc} card, and ${spadec} card'},
        {name: 'Ride the Bus', description: '+1 Mult per consecutive hand played without a scoring face card ${shadowc}(Currently +${jokerValue})'},
        {name: 'Shoot the Moon', description: '+13 Mult for each Queen held in hand'},
        {name: 'Scholar', description: 'Played Aces give +20 Chips and +4 Mult when scored'},
        {name: 'Smeared Joker', description: '${heartc} and ${diamondc} count as the same suit, ${spadec} and ${clubc} count as the same suit'},
        {name: 'Oops! All 6s', description: 'Double all listed ${probc}probabilities ${shadowc}(ex: ${probc}1 in 3 -> ${probc}2 in 3)'},
        {name: 'Four Fingers', description: 'All Flushes and Straights can be made with 4 cards'},
        {name: 'Gros Michel', description: '+15 Mult ${probc}1 in 4 chance this card is destroyed at the end of the round'},
        {name: 'Stuntman', description: '+300 Chips, -2 hand size'},
        {name: 'Hanging Chad', description: 'Retrigger first played card used in scoring'},
      ],
      [
        {name: 'Driver\'s License', description: '3 Mult if you have at least 16 Enhanced cards in your full deck ${shadowc}(Currently ${jokerValue})'},
        {name: 'Invisible Joker', description: 'After 3 rounds, sell this card to duplicate a random Joker ${shadowc}(Currently ${jokerValue}/3)'},
        {name: 'Astronomer', description: 'All ${planetc} cards and ${celestialc} in the shop are free'},
        {name: 'Burnt Joker', description: 'Upgrade the level of the first discarded poker hand each round'},
        {name: 'Dusk', description: 'Retrigger all played cards in final hand of round'},
        {name: 'Throwback', description: '0.25 Mult for each Blind skipped this run ${shadowc}(Currently ${1 + jokerValue * 0.25} Mult)'},
        {name: 'The Idol', description: 'Each played ${rankNames[Math.floor(Math.abs(jokerValue)/4) % 13]} of ${suitNames[Math.abs(jokerValue) % 4]} gives 2 Mult when scored ${shadowc}Card changes every round'},
        {name: 'Brainstorm', description: 'Copies the ability of the leftmost Joker'},
        {name: 'Satellite', description: 'Earn $1 at the end of round per unique ${planetc} card used this run ${shadowc}(Currently $${jokerValue})'},
        {name: 'Rough Gem', description: 'Played cards with ${diamondc} suit earn $1 when scored'}
      ],
      [
        {name: 'Bloodstone', description: '${probc}1 in 3 chance for played cards with ${heartc} suit to give 2 Mult when scored'},
        {name: 'Arrowhead', description: 'Played cards with ${spadec} suit give +50 Chips when scored'},
        {name: 'Onyx Agate', description: 'Played cards with ${clubc} suit give +8 Mult when scored'},
        {name: 'Caino', description: 'Gains 1 Mult when a face card is destroyed ${shadowc}(Currently ${1 + jokerValue} Mult)'},
        {name: 'Triboulet', description: 'Played Kings and Queens each give 2 Mult when scored'},
        {name: 'Yorick', description: '5 Mult only after using 23 discards ${shadowc}(Discards left ${jokerValue})'},
        {name: 'Chicot', description: 'Disables effect of every Boss Blind'},
        {name: 'Perkeo', description: 'Creates a ${negativec} copy of 1 random consumable card in your possession at the end of the shop'},
        {name: 'Certificate', description: 'When round begins, add a random playing card with a random seal to your hand'},
        {name: 'Bootstraps', description: '+2 Mult for every $5 you have ${shadowc}(Currently +${jokerValue * 2} Mult)'}
      ],
      [],
      [
        {name: 'Egg', description: 'Gains $3 of sell value at end of round'},
        {name: 'Burglar', description: 'When Blind is selected, gain +3 Hands and lose all discards'},
        {name: 'Blackboard', description: '3 Mult if all cards held in hand are ${spadec} or ${clubc}'},
        {name: 'Runner', description: 'Gains +10 Chips if played hand contains a Straight ${shadowc}(Currently +${20 + jokerValue * 10} Chips)'},
        {name: 'Ice Cream', description: '${jokerValue > 20 ? "" : "+"}${Math.max(0, 100 - jokerValue * 5)} Chips -5 Chips for every hand played'},
        {name: 'DNA', description: 'If first hand of round has only 1 card, add a permanent copy to deck and draw it to hand'},
        {name: 'Splash', description: 'Every  played card counts in scoring'},
        {name: 'Blue Joker', description: '+2 Chips for each remaining card in Deck ${shadowc}(Currently +${104 + jokerValue * 2} Chips)'},
        {name: 'Sixth Sense', description: 'If first hand of round is a single 6, destroy it and create a ${spectralc} card${roomc}'},
        {name: 'Constellation', description: 'Gains 0.1 Mult per ${planetc} card used ${shadowc}(Currently ${(Math.max(0, 10 + jokerValue))/10} Mult)'}
      ],
      [
        {name: 'Hiker', description: 'Every played card permanently gains +4 Chips when scored'},
        {name: 'Faceless Joker', description: 'Earn $5 if 3 or more face cards are discarded at the same time'},
        {name: 'Green Joker', description: '+1 Mult per hand played -1 Mult per discard ${shadowc}(Currently ${jokerValue >= 0 ? "+" : ""}${jokerValue} Mult)'},
        {name: 'Superposition', description: 'Create a ${tarotc} card if poker hand contains an Ace and a Straight${roomc}'},
        {name: 'To Do List', description: 'Earn $5 if poker hand is a Pair, poker hand changes on every payout'},
        {name: 'Cavendish', description: '3 Mult ${probc}1 in 1000 chance this card is destroy at end of round'},
        {name: 'Card Sharp', description: '3 Mult if played poker hand has already been played this round'},
        {name: 'Red Card', description: 'Gains +3 Mult when any Booster Pack is skipped ${shadowc}(Currently +${jokerValue * 3} Mult)'},
        {name: 'Madness', description: 'When Blind is selected, gain 0.5 Mult and destroy a random Joker ${shadowc}(Currently ${1 + jokerValue * 0.5})'},
        {name: 'Square Joker', description: 'Gain +4 Chips if played hand has exactly 4 card ${shadowc}(Currently +${16 + jokerValue * 4} Chips)'}
      ],
      [
        {name: 'Séance', description: 'If poker hand is a Straight Flush, craeate a random ${spectralc} card${roomc}'},
        {name: 'Riff-raff', description: 'When Blind is selected, create 2 ${commonc} Jokers${roomc}'},
        {name: 'Vampire', description: 'Gains 0.2 Mult per Enhanced card played, removes card Enhancement ${shadowc}(Currently ${(10 + jokerValue * 2) / 10} Mult)'},
        {name: 'Shortcut', description: 'Allows Straights to be made with gaps of 1 rank ${shadowc}(ex: 2 3 5 7 8)'},
        {name: 'Hologram', description: 'Gains 0.25 Mult  per playing card added to your deck ${shadowc}(Currently ${1 + jokerValue * 0.25} Mult)'},
        {name: 'Vagabond', description: 'Create a ${tarotc} card if hand is played with $3 or less'},
        {name: 'Baron', description: 'Each King held in hand gives 1.5 Mult'},
        {name: 'Cloud 9', description: 'Earn $1 for each 9 in your full deck at end of round ${shadowc}(Currently $${jokerValue})'},
        {name: 'Rocket', description: 'Earn $${1 + jokerValue * 2} at end of round. Gains $2 when Boss Blind is defeated'},
        {name: 'Obelisk', description: '0.2 Mult per consecutive hand played without playing your must played poker hand ${shadowc}(Currently ${(10 + jokerValue * 2) / 10} Mult)'}
      ],
      [
        {name: 'Midas Mask', description: 'All face cards become Gold cards when played'},
        {name: 'Luchador', description: 'Sell this card to disable the current Boss Blind'},
        {name: 'Photograph', description: 'First played face card gives 2 Mult when scored'},
        {name: 'Gift Card', description: 'Add $1 of sell value to every Joker and Consumable card at end of round'},
        {name: 'Turtle Bean', description: '${5 - jokerValue >= 0 ? "+" : ""}${5 - jokerValue} hand size, reduces by 1 every round'},
        {name: 'Erosion', description: '+4 Mult for each card below 52 in your full deck ${shadowc}(Currently ${jokerValue >= 0 ? "+" : ""}${jokerValue * 4})'},
        {name: 'Reserved Parking', description: 'Each face card held in hand has a ${probc}1 in 2 chance to give $1'},
        {name: 'Mail-In Rebate', description: 'Earn $3 for each discarded ${rankNames[Math.abs(jokerValue % 13)]}, rank changes every round'},
        {name: 'To the Moon', description: 'Earn an extra $1 of interest for every $5 you have at end of round'},
        {name: 'Hallucination', description: '${probc}1 in 2 chance to create a ${tarotc} card when any Booster Pack is opened${roomc}'}
      ],
      [
        {name: 'Sly Joker', description:  '+50 Chips if played hand contains a Pair'},
        {name: 'Wily Joker', description:  '+100 Chips if played hand contains a Three of a Kind'},
        {name: 'Clever Joker', description:  '+150 Chips if played hand contains a Four of a Kind'},
        {name: 'Devious Joker', description:  '+100 Chips if played hand contains a Straight'},
        {name: 'Crafty Joker', description:  '+80 Chips if played hand contains a Flush'},
        {name: 'Lucky Cat', description: 'Gains 0.2 Mult each time a Lucky card ${probc}successfully triggers ${shadowc}(currently ${(10 + jokerValue * 2) / 10} Mult)'},
        {name: 'Baseball Card', description: '${probc}Uncommon Jokers each give 1.5 Mult'},
        {name: 'Bull', description: '+2 Chips for each dollar you have ${shadowc}(Currently +${Math.max(0, jokerValue * 2)} Chips)'},
        {name: 'Diet Cola', description: 'Sell this card to create a free Double Tag'},
        {name: 'Trading Card', description: 'If first discard of round has only 1 card, destroy it and earn $3'}
      ],
      [
        {name: 'Flash Card', description: '+2 Mult per reroll in the shop Currently +X Mult)'},
        {name: 'Popcorn', description: '${jokerValue <= 5 ? "+" : ""}${Math.max(0, 20 - jokerValue * 4)} Mult -4 Mult per round played'},
        {name: 'Ramen', description: '${(Math.max(0, 200 - jokerValue)) / 100} Mult, loses 0.01 Mult per card discarded'},
        {name: 'Seltzer', description: 'Retrigger all cards played for the next 10 hands'},
        {name: 'Spare Trousers', description: 'Gain +2 Mult if played hand contains a Two Pair ${shadowc}(Currently +${jokerValue * 2} Mult)'},
        {name: 'Campfire', description: 'This Joker gains 0.5 Mult for each card sold, resets when Boss Blind is defeated ${shadowc}(Currently ${1 + jokerValue * 0.5} Mult)'},
        {name: 'Smiley Face', description: 'Played face cards give +4 Mult when scored'},
        {name: 'Ancient Joker', description: 'Each played card with ${[heartc, clubc, diamondc, spadec][Math.abs(jokerValue) % 4]} suit gives 1.5 Mult when scored ${shadowc}suit changes at end of round'},
        {name: 'Walkie Talkie', description: 'Each played 10 or 4 gives +10 Chips and +4 Mult when scored'},
        {name: 'Castle', description: 'This Joker gains +3 Chips per discarded ${[heartc, clubc, diamondc, spadec][Math.abs(jokerValue) % 4]} card, suit changes every round ${shadowc}(Currently +${jokerValue * 3} Chips)'}
      ]
    
]

export default JokersData